INSERT INTO curated_companies_source(name, location, companyType)
VALUES
('ICBC', 'China', 'company'),
('China Construction Bank', 'China', 'company'),
('Agricultural Bank of China', 'China', 'company'),
('Berkshire Hathaway', 'United States', 'company'),
('JPMorgan Chase', 'United States', 'company'),
('Bank of China', 'China', 'company'),
('Wells Fargo', 'United States', 'company'),
('Apple', 'United States', 'company'),
('ExxonMobil', 'United States', 'company'),
('Toyota Motor', 'Japan', 'company'),
('Bank of America', 'United States', 'company'),
('AT&T', 'United States', 'company'),
('Citigroup', 'United States', 'company'),
('HSBC Holdings', 'United Kingdom', 'company'),
('Verizon Communications', 'United States', 'company'),
('Wal-Mart Stores', 'United States', 'company'),
('PetroChina', 'China', 'company'),
('China Mobile', 'China', 'company'),
('Samsung Electronics', 'South Korea', 'company'),
('Ping An Insurance Group', 'China', 'company'),
('Allianz', 'Germany', 'company'),
('Volkswagen Group', 'Germany', 'company'),
('Microsoft', 'United States', 'company'),
('BNP Paribas', 'France', 'company'),
('Daimler', 'Germany', 'company'),
('AXA Group', 'France', 'company'),
('Alphabet', 'United States', 'company'),
('Chevron', 'United States', 'company'),
('Japan Post Holdings', 'Japan', 'company'),
('Total', 'France', 'company'),
('Sinopec', 'China', 'company'),
('Johnson & Johnson', 'United States', 'company'),
('Nestle', 'Switzerland', 'company'),
('Mitsubishi UFJ Financial', 'Japan', 'company'),
('Comcast', 'United States', 'company'),
('Bank of Communications', 'China', 'company'),
('Banco Santander', 'Spain', 'company'),
('China Merchants Bank', 'China', 'company'),
('Procter & Gamble', 'United States', 'company'),
('Ford Motor', 'United States', 'company'),
('IBM', 'United States', 'company'),
('UnitedHealth Group', 'United States', 'company'),
('General Motors', 'United States', 'company'),
('Nippon Telegraph & Tel', 'Japan', 'company'),
('BMW Group', 'Germany', 'company'),
('Pfizer', 'United States', 'company'),
('Novartis', 'Switzerland', 'company'),
('MetLife', 'United States', 'company'),
('China Life Insurance', 'China', 'company'),
('Royal Dutch Shell', 'Netherlands', 'company'),
('Siemens', 'Germany', 'company'),
('Royal Bank of Canada', 'Canada', 'company'),
('Gazprom', 'Russia', 'company'),
('UBS', 'Switzerland', 'company'),
('ING Group', 'Netherlands', 'company'),
('Anheuser-Busch InBev', 'Belgium', 'company'),
('Shanghai Pudong Development', 'China', 'company'),
('Commonwealth Bank', 'Australia', 'company'),
('Industrial Bank', 'China', 'company'),
('Intel', 'United States', 'company'),
('Citic Pacific', 'Hong Kong', 'company'),
('CVS Health', 'United States', 'company'),
('Cisco Systems', 'United States', 'company'),
('Itaú Unibanco Holding', 'Brazil', 'company'),
('China Minsheng Banking', 'China', 'company'),
('Prudential', 'United Kingdom', 'company'),
('TD Bank Group', 'Canada', 'company'),
('General Electric', 'United States', 'company'),
('Softbank', 'Japan', 'company'),
('Sumitomo Mitsui Financial', 'Japan', 'company'),
('Walt Disney', 'United States', 'company'),
('Westpac Banking Group', 'Australia', 'company'),
('Deutsche Telekom', 'Germany', 'company'),
('Honda Motor', 'Japan', 'company'),
('Rosneft', 'Russia', 'company'),
('Boeing', 'United States', 'company'),
('Goldman Sachs Group', 'United States', 'company'),
('Banco Bradesco', 'Brazil', 'company'),
('China Citic Bank', 'China', 'company'),
('Roche Holding', 'Switzerland', 'company'),
('Prudential Financial', 'United States', 'company'),
('Oracle', 'United States', 'company'),
('Coca-Cola', 'United States', 'company'),
('ANZ', 'Australia', 'company'),
('Nissan Motor', 'Japan', 'company'),
('Morgan Stanley', 'United States', 'company'),
('American International Group', 'United States', 'company'),
('National Australia Bank', 'Australia', 'company'),
('Sanofi', 'France', 'company'),
('PepsiCo', 'United States', 'company'),
('Bank of Nova Scotia', 'Canada', 'company'),
('Intesa Sanpaolo', 'Italy', 'company'),
('Merck', 'United States', 'company'),
('BASF', 'Germany', 'company'),
('American Express', 'United States', 'company'),
('United Technologies', 'United States', 'company'),
('Bayer', 'Germany', 'company'),
('Korea Electric Power', 'South Korea', 'company'),
('US Bancorp', 'United States', 'company'),
('GlaxoSmithKline', 'United Kingdom', 'company'),
('Munich Re', 'Germany', 'company'),
('EADS', 'France', 'company'),
('Sberbank', 'Russia', 'company'),
('Enel', 'Italy', 'company'),
('Telefónica', 'Spain', 'company'),
('Mizuho Financial', 'Japan', 'company'),
('Walgreens Boots Alliance', 'United States', 'company'),
('Hyundai Motor', 'South Korea', 'company'),
('Unilever', 'Netherlands', 'company'),
('Credit Agricole', 'France', 'company'),
('Dow Chemical', 'United States', 'company'),
('Home Depot', 'United States', 'company'),
('Saudi Basic Industries', 'Saudi Arabia', 'company'),
('China State Construction Engineering', 'China', 'company'),
('BBVA-Banco Bilbao Vizcaya', 'Spain', 'company'),
('Société Générale', 'France', 'company'),
('Hon Hai Precision', 'Taiwan', 'company'),
('Gilead Sciences', 'United States', 'company'),
('Swiss Re', 'Switzerland', 'company'),
('SAIC Motor', 'China', 'company'),
('Reliance Industries', 'India', 'company'),
('LukOil', 'Russia', 'company'),
('Capital One Financial', 'United States', 'company'),
('China Telecom', 'China', 'company'),
('Generali Group', 'Italy', 'company'),
('AIA Group', 'Hong Kong', 'company'),
('CK Hutchison', 'Hong Kong', 'company'),
('Zurich Insurance Group', 'Switzerland', 'company'),
('Medtronic', 'United States', 'company'),
('Orange', 'France', 'company'),
('Amgen', 'United States', 'company'),
('China Pacific Insurance', 'China', 'company'),
('Mondelēz International', 'United States', 'company'),
('CNOOC', 'China', 'company'),
('Allergan', 'United States', 'company'),
('Mitsubishi Corp', 'Japan', 'company'),
('Taiwan Semiconductor', 'Taiwan', 'company'),
('Honeywell International', 'United States', 'company'),
('China Everbright Bank', 'China', 'company'),
('Iberdrola', 'Spain', 'company'),
('Phillips 66', 'United States', 'company'),
('América Móvil', 'Mexico', 'company'),
('Bank of Montreal', 'Canada', 'company'),
('Lockheed Martin', 'United States', 'company'),
('Express Scripts', 'United States', 'company'),
('United Parcel Service', 'United States', 'company'),
('Renault', 'France', 'company'),
('Duke Energy', 'United States', 'company'),
('State Bank of India', 'India', 'company'),
('Nordea Bank', 'Sweden', 'company'),
('China Communications Construction', 'China', 'company'),
('Anthem', 'United States', 'company'),
('Banco do Brasil', 'Brazil', 'company'),
('PNC Financial Services', 'United States', 'company'),
('Caterpillar', 'United States', 'company'),
('Time Warner', 'United States', 'company'),
('KDDI', 'Japan', 'company'),
('AbbVie', 'United States', 'company'),
('McKesson', 'United States', 'company'),
('National Grid', 'United Kingdom', 'company'),
('Bank of New York Mellon', 'United States', 'company'),
('VINCI', 'France', 'company'),
('China Railway Group', 'China', 'company'),
('Target', 'United States', 'company'),
('Travelers', 'United States', 'company'),
('Hewlett Packard Enterprise', 'United States', 'company'),
('China Shenhua Energy', 'China', 'company'),
('Aetna', 'United States', 'company'),
('Qualcomm', 'United States', 'company'),
('Delta Air Lines', 'United States', 'company'),
('Lloyds Banking Group', 'United Kingdom', 'company'),
('Union Pacific', 'United States', 'company'),
('Chubb', 'Switzerland', 'company'),
('Alibaba', 'China', 'company'),
('AstraZeneca', 'United Kingdom', 'company'),
('Schlumberger', 'United States', 'company'),
('British American Tobacco', 'United Kingdom', 'company'),
('Hitachi', 'Japan', 'company'),
('SAP', 'Germany', 'company'),
('China Railway Construction', 'China', 'company'),
('People"s Insurance Company', 'China', 'company'),
('Manulife Financial', 'Canada', 'company'),
('Valero Energy', 'United States', 'company'),
('Philip Morris International', 'United States', 'company'),
('China Vanke', 'China', 'company'),
('Tokio Marine Holdings', 'Japan', 'company'),
('Aviva', 'United Kingdom', 'company'),
('Facebook', 'United States', 'company'),
('McDonald"s', 'United States', 'company'),
('Dalian Wanda Commercial Properties', 'China', 'company'),
('Exelon', 'United States', 'company'),
('Costco Wholesale', 'United States', 'company'),
('Sony', 'Japan', 'company'),
('Imperial Tobacco Group', 'United Kingdom', 'company'),
('UniCredit Group', 'Italy', 'company'),
('Visa', 'United States', 'company'),
('Brookfield Asset Management', 'Canada', 'company'),
('L"Oréal Group', 'France', 'company'),
('Jardine Matheson', 'Hong Kong', 'company'),
('3M', 'United States', 'company'),
('Tencent Holdings', 'China', 'company'),
('Allstate', 'United States', 'company'),
('Itochu', 'Japan', 'company'),
('Aflac', 'United States', 'company'),
('Lowe"s', 'United States', 'company'),
('Twenty-First Century Fox', 'United States', 'company'),
('BT Group', 'United Kingdom', 'company'),
('Cigna', 'United States', 'company'),
('Continental', 'Germany', 'company'),
('American Airlines Group', 'United States', 'company'),
('BlackRock', 'United States', 'company'),
('NextEra Energy', 'United States', 'company'),
('Southern', 'United States', 'company'),
('Danaher', 'United States', 'company'),
('SABMiller', 'United Kingdom', 'company'),
('Christian Dior', 'France', 'company'),
('Canadian Imperial Bank', 'Canada', 'company'),
('China Unicom', 'China', 'company'),
('Denso', 'Japan', 'company'),
('Oil & Natural Gas', 'India', 'company'),
('CRRC', 'China', 'company'),
('Japan Tobacco', 'Japan', 'company'),
('Kroger', 'United States', 'company'),
('Dai-ichi Life Insurance', 'Japan', 'company'),
('ABB', 'Switzerland', 'company'),
('Altria Group', 'United States', 'company'),
('Time Warner Cable', 'United States', 'company'),
('Deutsche Post', 'Germany', 'company'),
('KBC Group', 'Belgium', 'company'),
('Mitsui', 'Japan', 'company'),
('EMC', 'United States', 'company'),
('EI du Pont de Nemours', 'United States', 'company'),
('East Japan Railway', 'Japan', 'company'),
('Marathon Petroleum', 'United States', 'company'),
('Abbott Laboratories', 'United States', 'company'),
('Diageo', 'United Kingdom', 'company'),
('Amazon.com', 'United States', 'company'),
('Legal & General Group', 'United Kingdom', 'company'),
('General Dynamics', 'United States', 'company'),
('Seven & I Holdings', 'Japan', 'company'),
('Teva Pharmaceutical', 'Israel', 'company'),
('Surgutneftegas', 'Russia', 'company'),
('Eli Lilly', 'United States', 'company'),
('Fresenius', 'Germany', 'company'),
('Huaxia Bank', 'China', 'company'),
('Panasonic', 'Japan', 'company'),
('SK Holdings', 'South Korea', 'company'),
('Schneider Electric', 'France', 'company'),
('EDF', 'France', 'company'),
('John Deere', 'United States', 'company'),
('Nippon Steel & Sumitomo Metal', 'Japan', 'company'),
('Archer Daniels Midland', 'United States', 'company'),
('DBS Group', 'Singapore', 'company'),
('Bank of Beijing', 'China', 'company'),
('Canon', 'Japan', 'company'),
('Saint-Gobain', 'France', 'company'),
('United Continental Holdings', 'United States', 'company'),
('Volvo Group', 'Sweden', 'company'),
('HCA Holdings', 'United States', 'company'),
('FedEx', 'United States', 'company'),
('Nike', 'United States', 'company'),
('Telstra', 'Australia', 'company'),
('Danske Bank', 'Denmark', 'company'),
('Wesfarmers', 'Australia', 'company'),
('Orix', 'Japan', 'company'),
('ICICI Bank', 'India', 'company'),
('Thermo Fisher Scientific', 'United States', 'company'),
('Cardinal Health', 'United States', 'company'),
('Reynolds American', 'United States', 'company'),
('Hartford Financial Services', 'United States', 'company'),
('Shinhan Financial Group', 'South Korea', 'company'),
('American Electric', 'United States', 'company'),
('Bridgestone', 'Japan', 'company'),
('BB&T', 'United States', 'company'),
('HDFC Bank', 'India', 'company'),
('HP', 'United States', 'company'),
('Sun Life Financial', 'Canada', 'company'),
('Tata Motors', 'India', 'company'),
('Carrefour', 'France', 'company'),
('LyondellBasell Industries', 'Netherlands', 'company'),
('Kraft Heinz Company', 'Canada', 'company'),
('CNP Assurances', 'France', 'company'),
('Danone', 'France', 'company'),
('Central Japan Railway', 'Japan', 'company'),
('Samsung Life Insurance', 'South Korea', 'company'),
('Oversea-Chinese Banking', 'Singapore', 'company'),
('Gas Natural Fenosa', 'Spain', 'company'),
('Tokyo Electric Power', 'Japan', 'company'),
('Accenture', 'Ireland', 'company'),
('KIA Motors', 'South Korea', 'company'),
('Fubon Financial', 'Taiwan', 'company'),
('Heineken Holding', 'Netherlands', 'company'),
('Bristol-Myers Squibb', 'United States', 'company'),
('Mitsubishi Electric', 'Japan', 'company'),
('Raytheon', 'United States', 'company'),
('MS&AD Insurance', 'Japan', 'company'),
('Hyundai Mobis', 'South Korea', 'company'),
('New China Life Insurance', 'China', 'company'),
('Sun Hung Kai Properties', 'Hong Kong', 'company'),
('State Street', 'United States', 'company'),
('WPP', 'United Kingdom', 'company'),
('Power Corp of Canada', 'Canada', 'company'),
('Dominion Resources', 'United States', 'company'),
('Ericsson', 'Sweden', 'company'),
('Natixis', 'France', 'company'),
('Møller-Maersk', 'Denmark', 'company'),
('DNB', 'Norway', 'company'),
('BCE', 'Canada', 'company'),
('Citic Securities', 'China', 'company'),
('Inditex', 'Spain', 'company'),
('Carnival', 'United States', 'company'),
('Etisalat', 'United Arab Emirates', 'company'),
('Air Liquide', 'France', 'company'),
('Synchrony Financial', 'United States', 'company'),
('Eaton', 'Ireland', 'company'),
('Henkel', 'Germany', 'company'),
('Standard Bank Group', 'South Africa', 'company'),
('Cathay Financial', 'Taiwan', 'company'),
('Northrop Grumman', 'United States', 'company'),
('SingTel', 'Singapore', 'company'),
('Linde', 'Germany', 'company'),
('Poly Real Estate', 'China', 'company'),
('Greenland Holdings Group', 'China', 'company'),
('Huaneng Power International', 'China', 'company'),
('Discover Financial Services', 'United States', 'company'),
('Humana', 'United States', 'company'),
('Emerson Electric', 'United States', 'company'),
('Qatar National Bank', 'Qatar', 'company'),
('PG&E', 'United States', 'company'),
('Fuji Heavy Industries', 'Japan', 'company'),
('Merck', 'Germany', 'company'),
('United Overseas Bank', 'Singapore', 'company'),
('Commerzbank', 'Germany', 'company'),
('Ameriprise Financial', 'United States', 'company'),
('Haitong Securities', 'China', 'company'),
('Reckitt Benckiser Group', 'United Kingdom', 'company'),
('PTT PCL', 'Thailand', 'company'),
('SEB', 'Sweden', 'company'),
('NN Group', 'Netherlands', 'company'),
('China Resources Land', 'Hong Kong', 'company'),
('Fannie Mae', 'United States', 'company'),
('Southwest Airlines', 'United States', 'company'),
('Aegon', 'Netherlands', 'company'),
('Macquarie Group', 'Australia', 'company'),
('SunTrust Banks', 'United States', 'company'),
('BAE Systems', 'United Kingdom', 'company'),
('CaixaBank', 'Spain', 'company'),
('China Huarong Asset Management', 'China', 'company'),
('Baidu', 'China', 'company'),
('Charles Schwab', 'United States', 'company'),
('KB Financial Group', 'South Korea', 'company'),
('Old Mutual', 'United Kingdom', 'company'),
('Peugeot', 'France', 'company'),
('Automatic Data', 'United States', 'company'),
('Evergrande Real Estate', 'China', 'company'),
('Saudi Telecom', 'Saudi Arabia', 'company'),
('Svenska Handelsbanken', 'Sweden', 'company'),
('Tyson Foods', 'United States', 'company'),
('Wilmar International', 'Singapore', 'company'),
('Nokia', 'Finland', 'company'),
('Transneft', 'Russia', 'company'),
('Maybank', 'Malaysia', 'company'),
('Cheil Industries', 'South Korea', 'company'),
('Novo Nordisk', 'Denmark', 'company'),
('Marubeni', 'Japan', 'company'),
('Standard Life', 'United Kingdom', 'company'),
('Freddie Mac', 'United States', 'company'),
('Canadian National Railway', 'Canada', 'company'),
('SSE', 'United Kingdom', 'company'),
('BP', 'United Kingdom', 'company'),
('Indian Oil', 'India', 'company'),
('Sinohydro Group', 'China', 'company'),
('Swedbank', 'Sweden', 'company'),
('China Cinda Asset Management', 'China', 'company'),
('Tesco', 'United Kingdom', 'company'),
('CRH', 'Ireland', 'company'),
('CSX', 'United States', 'company'),
('SK Hynix', 'South Korea', 'company'),
('International Airlines', 'United Kingdom', 'company'),
('Principal Financial Group', 'United States', 'company'),
('Toyota Industries', 'Japan', 'company'),
('Mitsui Fudosan', 'Japan', 'company'),
('General Mills', 'United States', 'company'),
('Biogen Idec', 'United States', 'company'),
('Tata Consultancy Services', 'India', 'company'),
('Progressive', 'United States', 'company'),
('NKSJ Holdings', 'Japan', 'company'),
('Philips', 'Netherlands', 'company'),
('Starbucks', 'United States', 'company'),
('Femsa', 'Mexico', 'company'),
('Daiwa House Industry', 'Japan', 'company'),
('Michelin Group', 'France', 'company'),
('Consolidated Edison', 'United States', 'company'),
('Texas Instruments', 'United States', 'company'),
('Vodafone', 'United Kingdom', 'company'),
('Lincoln National', 'United States', 'company'),
('Celgene', 'United States', 'company'),
('Magna International', 'Canada', 'company'),
('Edison International', 'United States', 'company'),
('NTPC', 'India', 'company'),
('Cheung Kong Property Holdings', 'Hong Kong', 'company'),
('Midea Group', 'China', 'company'),
('Sumitomo Mitsui Trust', 'Japan', 'company'),
('HDFC', 'India', 'company'),
('Thomson Reuters', 'United States', 'company'),
('EXOR', 'Italy', 'company'),
('CenturyLink', 'United States', 'company'),
('Norfolk Southern', 'United States', 'company'),
('Eni', 'Italy', 'company'),
('Sempra Energy', 'United States', 'company'),
('Petrobras', 'Brazil', 'company'),
('TJX Cos', 'United States', 'company'),
('Public Service Enterprise Group', 'United States', 'company'),
('Talanx', 'Germany', 'company'),
('Mitsubishi Heavy Industries', 'Japan', 'company'),
('Richemont', 'Switzerland', 'company'),
('Fujifilm Holdings', 'Japan', 'company'),
('MasterCard', 'United States', 'company'),
('Vivendi', 'France', 'company'),
('Aon', 'United Kingdom', 'company'),
('Barclays', 'United Kingdom', 'company'),
('Monsanto', 'United States', 'company'),
('Chubu Electric Power', 'Japan', 'company'),
('PayPal', 'United States', 'company'),
('CBS', 'United States', 'company'),
('International Paper', 'United States', 'company'),
('PPL', 'United States', 'company'),
('GDF SUEZ', 'France', 'company'),
('Bank Rakyat Indonesia', 'Indonesia', 'company'),
('Paccar', 'United States', 'company'),
('Poste Italiane', 'Italy', 'company'),
('Las Vegas Sands', 'United States', 'company'),
('National Commercial Bank', 'Saudi Arabia', 'company'),
('Fosun International', 'China', 'company'),
('Metallurgical Corp of China', 'China', 'company'),
('Erste Group Bank', 'Austria', 'company'),
('EDP-Energias de Portugal', 'Portugal', 'company'),
('Glencore International', 'Switzerland', 'company'),
('Swiss Life Holding', 'Switzerland', 'company'),
('Steinhoff International', 'South Africa', 'company'),
('Statoil', 'Norway', 'company'),
('CLP Holdings', 'Hong Kong', 'company'),
('Syngenta', 'Switzerland', 'company'),
('Country Garden Holdings', 'China', 'company'),
('The Priceline Group', 'United States', 'company'),
('GF Securities', 'China', 'company'),
('Isbank', 'Turkey', 'company'),
('Deutsche Bank', 'Germany', 'company'),
('Sampo', 'Finland', 'company'),
('Royal Bank of Scotland', 'United Kingdom', 'company'),
('Koç Holding', 'Turkey', 'company'),
('British Sky Broadcasting', 'United Kingdom', 'company'),
('Bharti Airtel', 'India', 'company'),
('Pernod Ricard', 'France', 'company'),
('BHP Billiton', 'Australia', 'company'),
('Fifth Third Bancorp', 'United States', 'company'),
('Marsh & McLennan', 'United States', 'company'),
('PPG', 'United States', 'company'),
('H&M', 'Sweden', 'company'),
('Illinois Tool Works', 'United States', 'company'),
('Credit Suisse Group', 'Switzerland', 'company'),
('Bank Mandiri', 'Indonesia', 'company'),
('Sasol', 'South Africa', 'company'),
('Tenaga Nasional', 'Malaysia', 'company'),
('Coal India', 'India', 'company'),
('eBay', 'United States', 'company'),
('Compass Group', 'United Kingdom', 'company'),
('Johnson Controls', 'United States', 'company'),
('Swisscom', 'Switzerland', 'company'),
('China Reinsurance Group', 'China', 'company'),
('Xcel Energy', 'United States', 'company'),
('Stryker', 'United States', 'company'),
('Rio Tinto', 'United Kingdom', 'company'),
('Grupo ACS', 'Spain', 'company'),
('Associated British Foods', 'United Kingdom', 'company'),
('Hilton Worldwide Holdings', 'United States', 'company'),
('Kimberly-Clark', 'United States', 'company'),
('Daikin Industries', 'Japan', 'company'),
('Deutsche Lufthansa', 'Germany', 'company'),
('Viacom', 'United States', 'company'),
('ConocoPhillips', 'United States', 'company'),
('Garanti Bank', 'Turkey', 'company'),
('Teliasonera', 'Sweden', 'company'),
('Axis Bank', 'India', 'company'),
('HeidelbergCement', 'Germany', 'company'),
('Royal Ahold', 'Netherlands', 'company'),
('Swire Pacific', 'Hong Kong', 'company'),
('Praxair', 'United States', 'company'),
('Suzuki Motor', 'Japan', 'company'),
('Samsung Fire & Marine', 'South Korea', 'company'),
('Omnicom Group', 'United States', 'company'),
('Ecolab', 'United States', 'company'),
('Ally Financial', 'United States', 'company'),
('AmerisourceBergen', 'United States', 'company'),
('E.ON', 'Germany', 'company'),
('Komatsu', 'Japan', 'company'),
('Corning', 'United States', 'company'),
('TE Connectivity', 'Switzerland', 'company'),
('CIC Group', 'France', 'company'),
('Colgate-Palmolive', 'United States', 'company'),
('SK Innovation', 'South Korea', 'company'),
('FirstRand', 'South Africa', 'company'),
('Fiat Chrysler Automobiles', 'United Kingdom', 'company'),
('Level 3 Communications', 'United States', 'company'),
('Larsen & Toubro', 'India', 'company'),
('SK Telecom', 'South Korea', 'company'),
('Formosa Petrochemical', 'Taiwan', 'company'),
('Kubota', 'Japan', 'company'),
('Dongfeng Motor Group', 'China', 'company'),
('AMP', 'Australia', 'company'),
('Ageas', 'Netherlands', 'company'),
('Cummins', 'United States', 'company'),
('FirstEnergy', 'United States', 'company'),
('Mapfre', 'Spain', 'company'),
('Macy"s', 'United States', 'company'),
('Standard Chartered', 'United Kingdom', 'company'),
('DISH Network', 'United States', 'company'),
('Sysco', 'United States', 'company'),
('JBS', 'Brazil', 'company'),
('Baxter International', 'United States', 'company'),
('Thales', 'France', 'company'),
('Akzo Nobel', 'Netherlands', 'company'),
('MTN Group', 'South Africa', 'company'),
('Becton Dickinson', 'United States', 'company'),
('Simon Property Group', 'United States', 'company'),
('Veolia Environnement', 'France', 'company'),
('Shin-Etsu Chemical', 'Japan', 'company'),
('Investor AB', 'Sweden', 'company'),
('Cognizant Technology', 'United States', 'company'),
('Suncorp Group', 'Australia', 'company'),
('GFNorte', 'Mexico', 'company'),
('Kyocera', 'Japan', 'company'),
('Astellas Pharma', 'Japan', 'company'),
('Akbank', 'Turkey', 'company'),
('RELX Group', 'United Kingdom', 'company'),
('Siam Commercial Bank', 'Thailand', 'company'),
('M&T Bank', 'United States', 'company'),
('Allied Irish Banks', 'Ireland', 'company'),
('Couche Tard', 'Canada', 'company'),
('Air Products & Chemicals', 'United States', 'company'),
('XL Group', 'Ireland', 'company'),
('Enbridge', 'Canada', 'company'),
('Kering', 'France', 'company'),
('Al Rajhi Bank', 'Saudi Arabia', 'company'),
('China Taiping Insurance', 'Hong Kong', 'company'),
('Banco de Sabadell', 'Spain', 'company'),
('Mazda Motor', 'Japan', 'company'),
('New World Development', 'Hong Kong', 'company'),
('Waste Management', 'United States', 'company'),
('Guosen Securities', 'China', 'company'),
('Publicis Groupe', 'France', 'company'),
('Emirates NBD', 'United Arab Emirates', 'company'),
('Suncor Energy', 'Canada', 'company'),
('Chinatrust Financial', 'Taiwan', 'company'),
('Aisin Seiki', 'Japan', 'company'),
('LafargeHolcim', 'Switzerland', 'company'),
('MTR', 'Hong Kong', 'company'),
('JFE Holdings', 'Japan', 'company'),
('Vale', 'Brazil', 'company'),
('NXP Semiconductors', 'Netherlands', 'company'),
('Evonik', 'Germany', 'company'),
('Tesoro', 'United States', 'company'),
('Wheelock', 'Hong Kong', 'company'),
('LG Chem', 'South Korea', 'company'),
('Rogers Communications', 'Canada', 'company'),
('Atlas Copco', 'Sweden', 'company'),
('Kasikornbank', 'Thailand', 'company'),
('ArcelorMittal', 'Luxembourg', 'company'),
('SCA', 'Sweden', 'company'),
('Saudi Electricity', 'Saudi Arabia', 'company'),
('QBE Insurance Group', 'Australia', 'company'),
('Bouygues', 'France', 'company'),
('National Bank of Canada', 'Canada', 'company'),
('Whirlpool', 'United States', 'company'),
('Dollar General', 'United States', 'company'),
('Posco', 'South Korea', 'company'),
('Adidas', 'Germany', 'company'),
('Capgemini', 'France', 'company'),
('ASML Holding', 'Netherlands', 'company'),
('Woori Bank', 'South Korea', 'company'),
('Public Bank', 'Malaysia', 'company'),
('Mylan', 'United States', 'company'),
('Micron Technology', 'United States', 'company'),
('Repsol', 'Spain', 'company'),
('Daiwa Securities', 'Japan', 'company'),
('Ferrovial', 'Spain', 'company'),
('Resona Holdings', 'Japan', 'company'),
('Regions Financial', 'United States', 'company'),
('Otsuka Holding', 'Japan', 'company'),
('Infosys', 'India', 'company'),
('Liberty Global', 'United Kingdom', 'company'),
('IntercontinentalExchange', 'United States', 'company'),
('Murata Manufacturing', 'Japan', 'company'),
('Kinder Morgan', 'United States', 'company'),
('Sodexo', 'France', 'company'),
('Mitsubishi Estate', 'Japan', 'company'),
('Hana Financial Group', 'South Korea', 'company'),
('Huatai Securities', 'China', 'company'),
('Telenor', 'Norway', 'company'),
('CME Group', 'United States', 'company'),
('Franklin Resources', 'United States', 'company'),
('T&D Holdings', 'Japan', 'company'),
('Unibail-Rodamco', 'France', 'company'),
('Eversource Energy', 'United States', 'company'),
('Fairfax Financial', 'Canada', 'company'),
('Northern Trust', 'United States', 'company'),
('China Eastern Airlines', 'China', 'company'),
('Daiichi Sankyo', 'Japan', 'company'),
('Tokyo Gas', 'Japan', 'company'),
('Atlantia', 'Italy', 'company'),
('Legend Holding', 'China', 'company'),
('Grupo Mexico', 'Mexico', 'company'),
('Sumitomo Electric', 'Japan', 'company'),
('DTE Energy', 'United States', 'company'),
('Falabella', 'Chile', 'company'),
('TELUS', 'Canada', 'company'),
('Delphi Automotive', 'United Kingdom', 'company'),
('Toray Industries', 'Japan', 'company'),
('Sabanci Holding', 'Turkey', 'company'),
('Bank Central Asia', 'Indonesia', 'company'),
('Unum', 'United States', 'company'),
('Siam Cement', 'Thailand', 'company'),
('Halliburton', 'United States', 'company'),
('Henderson Land', 'Hong Kong', 'company'),
('Daqin Railway', 'China', 'company'),
('Aeon', 'Japan', 'company'),
('VTB Bank', 'Russia', 'company'),
('Telecom Italia', 'Italy', 'company'),
('Guotai Junan Securities', 'China', 'company'),
('J Sainsbury', 'United Kingdom', 'company'),
('Shire', 'Ireland', 'company'),
('Citizens Financial Group', 'United States', 'company'),
('Kellogg', 'United States', 'company'),
('Applied Materials', 'United States', 'company'),
('Sumitomo Realty', 'Japan', 'company'),
('Fujitsu', 'Japan', 'company'),
('Best Buy', 'United States', 'company'),
('China Merchants Shekou Industrial Zone Holdings', 'China', 'company'),
('Norilsk Nickel', 'Russia', 'company'),
('Bankia', 'Spain', 'company'),
('Shenwan Hongyuan Group', 'China', 'company'),
('George Weston', 'Canada', 'company'),
('Occidental Petroleum', 'United States', 'company'),
('Bunge', 'United States', 'company'),
('Sumitomo Corp', 'Japan', 'company'),
('Bank of Nanjing', 'China', 'company'),
('Industrial Bank of Korea', 'South Korea', 'company'),
('Agrium', 'Canada', 'company'),
('Yum Brands', 'United States', 'company'),
('Bharat Petroleum', 'India', 'company'),
('Dentsu', 'Japan', 'company'),
('Constellation Brands', 'United States', 'company'),
('Scor', 'France', 'company'),
('Chunghwa Telecom', 'Taiwan', 'company'),
('Stanley Black & Decker', 'United States', 'company'),
('Grupo Aval', 'Colombia', 'company'),
('First Gulf Bank', 'United Arab Emirates', 'company'),
('VF', 'United States', 'company'),
('Telekom Indonesia', 'Indonesia', 'company'),
('LG Display', 'South Korea', 'company'),
('ThyssenKrupp Group', 'Germany', 'company'),
('Ingersoll-Rand', 'Ireland', 'company'),
('West Japan Railway', 'Japan', 'company'),
('Huadian Power International', 'China', 'company'),
('Liberty Interactive', 'United States', 'company'),
('Takeda Pharmaceutical', 'Japan', 'company'),
('WH Group', 'Hong Kong', 'company'),
('CIMB Group Holdings', 'Malaysia', 'company'),
('JX Holdings', 'Japan', 'company'),
('Kweichow Moutai', 'China', 'company'),
('Asahi Group Holdings', 'Japan', 'company'),
('Porsche Automobil Holding', 'Germany', 'company'),
('Nan Ya Plastics', 'Taiwan', 'company'),
('China Resources Power', 'Hong Kong', 'company'),
('China Zheshang Bank', 'China', 'company'),
('China Southern Airlines', 'China', 'company'),
('China Yangtze Power', 'China', 'company'),
('Altice', 'Luxembourg', 'company'),
('Xerox', 'United States', 'company'),
('Naspers', 'South Africa', 'company'),
('Sekisui House', 'Japan', 'company'),
('National Bank of Abu Dhabi', 'United Arab Emirates', 'company'),
('Safran', 'France', 'company'),
('Asahi Kasei', 'Japan', 'company'),
('Gree Electric Appliances', 'China', 'company'),
('Wolseley', 'Switzerland', 'company'),
('Broadcom', 'United States', 'company'),
('Republic Services', 'United States', 'company'),
('Bank of Ireland', 'Ireland', 'company'),
('Novatek', 'Russia', 'company'),
('Western Digital', 'United States', 'company'),
('China Merchants Securities', 'China', 'company'),
('Sumitomo Chemical', 'Japan', 'company'),
('Kao Corp', 'Japan', 'company'),
('Formosa Chemicals', 'Taiwan', 'company'),
('Estée Lauder', 'United States', 'company'),
('Japan Airlines', 'Japan', 'company'),
('Ecopetrol', 'Colombia', 'company'),
('Deutsche Boerse', 'Germany', 'company'),
('Fidelity National Information', 'United States', 'company'),
('Yara International', 'Norway', 'company'),
('China Galaxy Securities', 'China', 'company'),
('American Tower', 'United States', 'company'),
('VMware', 'United States', 'company'),
('Shengjing Bank', 'China', 'company'),
('RWE Group', 'Germany', 'company'),
('Longfor Properties', 'China', 'company'),
('Centrica', 'United Kingdom', 'company'),
('Swatch Group', 'Switzerland', 'company'),
('China Energy Engineering', 'China', 'company'),
('Bank of Ningbo', 'China', 'company'),
('Toyota Tsusho', 'Japan', 'company'),
('Snam', 'Italy', 'company'),
('Hong Kong Exchanges', 'Hong Kong', 'company'),
('Anglo American', 'United Kingdom', 'company'),
('Isuzu Motors', 'Japan', 'company'),
('L Brands', 'United States', 'company'),
('Fanuc', 'Japan', 'company'),
('Anhui Conch Cement', 'China', 'company'),
('GD Power Development', 'China', 'company'),
('BYD', 'China', 'company'),
('Sherwin-Williams', 'United States', 'company'),
('Rolls-Royce Holdings', 'United Kingdom', 'company'),
('Royal Caribbean Cruises', 'United States', 'company'),
('Loews', 'United States', 'company'),
('Sanlam', 'South Africa', 'company'),
('Toshiba', 'Japan', 'company'),
('Baoshan Iron & Steel', 'China', 'company'),
('WEC Energy Group', 'United States', 'company'),
('Essilor International', 'France', 'company'),
('Tohoku Electric Power', 'Japan', 'company'),
('Ryanair Holdings', 'Ireland', 'company'),
('Bancolombia', 'Colombia', 'company'),
('Luxottica Group', 'Italy', 'company'),
('Valeo', 'France', 'company'),
('Canadian Natural Resources', 'Canada', 'company'),
('KeyCorp', 'United States', 'company'),
('Credicorp', 'Peru', 'company'),
('Samba Financial Group', 'Saudi Arabia', 'company'),
('Freeport', 'United States', 'company'),
('Ross Stores', 'United States', 'company'),
('General Growth Properties', 'United States', 'company'),
('Metro Group', 'Germany', 'company'),
('PotashCorp', 'Canada', 'company'),
('Voya Financial', 'United States', 'company'),
('Hyundai Steel', 'South Korea', 'company'),
('CEZ Group', 'Czech Republic', 'company'),
('Ricoh', 'Japan', 'company'),
('HAL Trust', 'Netherlands', 'company'),
('YPF', 'Argentina', 'company'),
('Solvay', 'Belgium', 'company'),
('Parker-Hannifin', 'United States', 'company'),
('TransCanada', 'Canada', 'company'),
('AutoZone', 'United States', 'company'),
('Wipro', 'India', 'company'),
('Anadarko Petroleum', 'United States', 'company'),
('Alcoa', 'United States', 'company'),
('Kingfisher', 'United Kingdom', 'company'),
('Textron', 'United States', 'company'),
('Woolworths', 'Australia', 'company'),
('Abu Dhabi Commercial Bank', 'United Arab Emirates', 'company'),
('Nidec', 'Japan', 'company'),
('AerCap Holdings', 'Netherlands', 'company'),
('Scentre Group', 'Australia', 'company'),
('CNH Industrial', 'United Kingdom', 'company'),
('Fast Retailing', 'Japan', 'company'),
('Prologis', 'United States', 'company'),
('Kone', 'Finland', 'company'),
('Eastman Chemical', 'United States', 'company'),
('UPM-Kymmene', 'Finland', 'company'),
('Kansai Electric Power', 'Japan', 'company'),
('KPN', 'Netherlands', 'company'),
('Mosaic', 'United States', 'company'),
('Magnit', 'Russia', 'company'),
('National Bank of Kuwait', 'Kuwait', 'company'),
('ZTE', 'Hong Kong', 'company'),
('Marriott International', 'United States', 'company'),
('London Stock Exchange', 'United Kingdom', 'company'),
('Bangkok Bank', 'Thailand', 'company'),
('Devon Energy', 'United States', 'company'),
('All Nippon Airways', 'Japan', 'company'),
('ITC', 'India', 'company'),
('Baxalta', 'United States', 'company'),
('Charter Communications', 'United States', 'company'),
('Canadian Pacific Railway', 'Canada', 'company'),
('CarMax', 'United States', 'company'),
('Invesco', 'United States', 'company'),
('Kuehne + Nagel', 'Switzerland', 'company'),
('Cathay Pacific Airways', 'Hong Kong', 'company'),
('Shanghai Electric Group', 'China', 'company'),
('Orient Securities', 'China', 'company'),
('Mega Financial Holding', 'Taiwan', 'company'),
('Mercantil Servicios', 'Venezuela', 'company'),
('CGN Power', 'China', 'company'),
('Chongqing Changan Auto', 'China', 'company'),
('Great Wall Motor', 'China', 'company'),
('Schaeffler', 'Germany', 'company'),
('Baker Hughes', 'United States', 'company'),
('Deutsche Annington Immobilien', 'Germany', 'company'),
('JD.com', 'China', 'company'),
('Bank of Baroda', 'India', 'company'),
('Inpex', 'Japan', 'company'),
('Land Securities Group', 'United Kingdom', 'company'),
('Assa Abloy', 'Sweden', 'company'),
('Bâloise Group', 'Switzerland', 'company'),
('EOG Resources', 'United States', 'company'),
('Expedia', 'United States', 'company'),
('Cenovus Energy', 'Canada', 'company'),
('Kohl"s', 'United States', 'company'),
('Tatneft', 'Russia', 'company'),
('Datang International Power', 'China', 'company'),
('IDGC Holding', 'Russia', 'company'),
('Sime Darby', 'Malaysia', 'company'),
('LG Electronics', 'South Korea', 'company'),
('OMV Group', 'Austria', 'company'),
('Marks & Spencer', 'United Kingdom', 'company'),
('Guangdong Wens Foodstuffs Group', 'China', 'company'),
('CSL', 'Australia', 'company'),
('Hyundai Heavy Industries', 'South Korea', 'company'),
('PKN Orlen', 'Poland', 'company'),
('Link REIT', 'Hong Kong', 'company'),
('KT Corp', 'South Korea', 'company'),
('Reinsurance Group of America', 'United States', 'company'),
('O"Reilly Automotive', 'United States', 'company'),
('LG Corp', 'South Korea', 'company'),
('Lennar', 'United States', 'company'),
('Delhaize Group', 'Belgium', 'company'),
('Westfield', 'Australia', 'company'),
('Sinopharm Group', 'China', 'company'),
('Saudi British Bank', 'Saudi Arabia', 'company'),
('Discovery Communications', 'United States', 'company'),
('Osaka Gas', 'Japan', 'company'),
('China Fortune Land Development', 'China', 'company'),
('Entergy', 'United States', 'company'),
('Nucor', 'United States', 'company'),
('Zhejiang Zheneng Electric Power', 'China', 'company'),
('Adobe Systems', 'United States', 'company'),
('Riyad Bank', 'Saudi Arabia', 'company'),
('Chongqing Rural Bank', 'China', 'company'),
('Lenovo Group', 'China', 'company'),
('Genuine Parts', 'United States', 'company'),
('Activision Blizzard', 'United States', 'company'),
('Quanta Computer', 'Taiwan', 'company'),
('Schindler Holding', 'Switzerland', 'company'),
('Welltower', 'United States', 'company'),
('Krung Thai Bank', 'Thailand', 'company'),
('TD Ameritrade Holding', 'United States', 'company'),
('Valeant Pharmaceuticals', 'Canada', 'company'),
('Ooredoo Telecom', 'Qatar', 'company'),
('Shimao Property Holdings', 'Hong Kong', 'company'),
('Mitsubishi Chemical', 'Japan', 'company'),
('China Shipbuilding Industry', 'China', 'company'),
('Rakuten', 'Japan', 'company'),
('Secom', 'Japan', 'company'),
('Dollar Tree', 'United States', 'company'),
('BOE Technology Group', 'China', 'company'),
('Ameren', 'United States', 'company'),
('Bank of East Asia', 'Hong Kong', 'company'),
('DR Horton', 'United States', 'company'),
('Alliance Data Systems', 'United States', 'company'),
('Formosa Plastics', 'Taiwan', 'company'),
('Everbright Securities', 'China', 'company'),
('Nielsen', 'United States', 'company'),
('Pegatron', 'Taiwan', 'company'),
('SM Investments', 'Philippines', 'company'),
('Punjab National Bank', 'India', 'company'),
('Markel', 'United States', 'company'),
('Recruit Holdings', 'Japan', 'company'),
('Shanghai International Port', 'China', 'company'),
('Weyerhaeuser', 'United States', 'company'),
('Banque Saudi Fransi', 'Saudi Arabia', 'company'),
('Hormel Foods', 'United States', 'company'),
('Skanska', 'Sweden', 'company'),
('Power Assets Holdings', 'Hong Kong', 'company'),
('Ajinomoto', 'Japan', 'company'),
('Gap', 'United States', 'company'),
('Keppel Corp', 'Singapore', 'company'),
('Halkbank', 'Turkey', 'company'),
('Eiffage', 'France', 'company'),
('Hermès International', 'France', 'company'),
('Aena', 'Spain', 'company'),
('Itaúsa', 'Brazil', 'company'),
('Tokyu', 'Japan', 'company'),
('Grupo Televisa', 'Mexico', 'company'),
('AES', 'United States', 'company'),
('EnBW-Energie Baden', 'Germany', 'company'),
('Kirin Holdings', 'Japan', 'company'),
('Bank Hapoalim', 'Israel', 'company'),
('British Land', 'United Kingdom', 'company'),
('Everest Re Group', 'Bermuda', 'company'),
('BRF', 'Brazil', 'company'),
('Insurance Australia Group', 'Australia', 'company'),
('Emaar Properties', 'United Arab Emirates', 'company'),
('DaVita', 'United States', 'company'),
('Singapore Airlines', 'Singapore', 'company'),
('Husky Energy', 'Canada', 'company'),
('Hanwha Corp', 'South Korea', 'company'),
('Tyco International', 'Switzerland', 'company'),
('Kotak Mahindra Bank', 'India', 'company'),
('Williams', 'United States', 'company'),
('Mahindra & Mahindra', 'India', 'company'),
('First Data', 'United States', 'company'),
('Unipol Gruppo', 'Italy', 'company'),
('Huishang Bank', 'China', 'company'),
('Navient', 'United States', 'company'),
('DP World', 'United Arab Emirates', 'company'),
('Vestas Wind Systems', 'Denmark', 'company'),
('Cemex', 'Mexico', 'company'),
('Aluminum Corp of China', 'China', 'company'),
('McGraw-Hill', 'United States', 'company'),
('National Oilwell Varco', 'United States', 'company'),
('Lotte Shopping', 'South Korea', 'company'),
('Barrick Gold', 'Canada', 'company'),
('S-Oil', 'South Korea', 'company'),
('CIT Group', 'United States', 'company'),
('Vornado Realty', 'United States', 'company'),
('Equity Residential', 'United States', 'company'),
('Avalonbay Communities', 'United States', 'company'),
('Xiamen C&D', 'China', 'company'),
('Lear', 'United States', 'company'),
('CMS Energy', 'United States', 'company'),
('WW Grainger', 'United States', 'company'),
('First Republic Bank', 'United States', 'company'),
('Randstad Holding', 'Netherlands', 'company'),
('Yahoo', 'United States', 'company'),
('CapitaLand', 'Singapore', 'company'),
('Towngas', 'Hong Kong', 'company'),
('Hess', 'United States', 'company'),
('Huntington Bancshares', 'United States', 'company'),
('Beiersdorf', 'Germany', 'company'),
('Flextronics International', 'Singapore', 'company'),
('Stora Enso', 'Finland', 'company'),
('Public Storage', 'United States', 'company'),
('Campbell Soup', 'United States', 'company'),
('Obayashi', 'Japan', 'company'),
('Johnson Matthey', 'United Kingdom', 'company'),
('Grupo Inbursa', 'Mexico', 'company'),
('PKO Bank Polski', 'Poland', 'company'),
('Taisei', 'Japan', 'company'),
('St Jude Medical', 'United States', 'company'),
('JM Smucker', 'United States', 'company'),
('Power Grid of India', 'India', 'company'),
('HCL Technologies', 'India', 'company'),
('Ultrapar Participacoes', 'Brazil', 'company'),
('Crown Castle International', 'United States', 'company'),
('Canara Bank', 'India', 'company'),
('VakifBank', 'Turkey', 'company'),
('Banco De Venezuela', 'Venezuela', 'company'),
('Inner Mongolia Yili', 'China', 'company'),
('Lotte Chemical', 'South Korea', 'company'),
('Braskem', 'Brazil', 'company'),
('Finatis', 'France', 'company'),
('Bank of Greece', 'Greece', 'company'),
('Uni-President', 'Taiwan', 'company'),
('CGI Group', 'Canada', 'company'),
('Qingdao Haier', 'China', 'company'),
('LabCorp', 'United States', 'company'),
('Raiffeisen Bank International', 'Austria', 'company'),
('Investec', 'United Kingdom', 'company'),
('Mediobanca', 'Italy', 'company'),
('Universal Health', 'United States', 'company'),
('Voestalpine', 'Austria', 'company'),
('China National Nuclear Power', 'China', 'company'),
('Guangzhou R&F', 'China', 'company'),
('Mohawk Industries', 'United States', 'company'),
('Amcor', 'Australia', 'company'),
('WestRock', 'United States', 'company'),
('Fidelity National Financial', 'United States', 'company'),
('Annaly Capital Management', 'United States', 'company'),
('Infineon Technologies', 'Germany', 'company'),
('Cincinnati Financial', 'United States', 'company'),
('Turkish Airlines', 'Turkey', 'company'),
('CBRE Group', 'United States', 'company'),
('Boston Scientific', 'United States', 'company'),
('Zimmer Holdings', 'United States', 'company'),
('Onex', 'Canada', 'company'),
('Newmont Mining', 'United States', 'company'),
('Boston Properties', 'United States', 'company'),
('Suntory Beverage & Food', 'Japan', 'company'),
('Suning Appliance', 'China', 'company'),
('Mediatek', 'Taiwan', 'company'),
('China Coal Energy', 'China', 'company'),
('Goodyear', 'United States', 'company'),
('SDIC Power Holdings', 'China', 'company'),
('Grupa PZU', 'Poland', 'company'),
('Grupo Bimbo', 'Mexico', 'company'),
('BAIC Motor', 'China', 'company'),
('C.H. Robinson Worldwide', 'United States', 'company'),
('MGM Resorts', 'United States', 'company'),
('Whole Foods Market', 'United States', 'company'),
('Bed Bath & Beyond', 'United States', 'company'),
('ConAgra Foods', 'United States', 'company'),
('Beijing Enterprises', 'Hong Kong', 'company'),
('Shimizu', 'Japan', 'company'),
('Daito Trust Construction', 'Japan', 'company'),
('Arrow Electronics', 'United States', 'company'),
('Nordstrom', 'United States', 'company'),
('Keyence', 'Japan', 'company'),
('Cencosud', 'Chile', 'company'),
('Fortis (Canada)', 'Canada', 'company'),
('Spectra Energy', 'United States', 'company'),
('NEC', 'Japan', 'company'),
('Transocean', 'Switzerland', 'company'),
('Henry Schein', 'United States', 'company'),
('Mitsubishi Motors', 'Japan', 'company'),
('Avnet', 'United States', 'company'),
('Finmeccanica', 'Italy', 'company'),
('Quest Diagnostics', 'United States', 'company'),
('Schroders', 'United Kingdom', 'company'),
('TDK', 'Japan', 'company'),
('Dr Pepper Snapple Group', 'United States', 'company'),
('TUI', 'Germany', 'company'),
('PTT Global Chemical', 'Thailand', 'company'),
('Hershey', 'United States', 'company'),
('TCL Corp', 'China', 'company'),
('Founder Securities', 'China', 'company'),
('Carlsberg', 'Denmark', 'company'),
('Fiserv', 'United States', 'company'),
('Korea Gas', 'South Korea', 'company'),
('Rockwell Automation', 'United States', 'company'),
('WR Berkley', 'United States', 'company'),
('Pgnig Group', 'Poland', 'company'),
('ATOS', 'France', 'company'),
('Hydro One', 'Canada', 'company'),
('Bank Leumi', 'Israel', 'company'),
('Kuwait Finance House', 'Kuwait', 'company'),
('Dubai Islamic Bank', 'United Arab Emirates', 'company'),
('Axiata Group', 'Malaysia', 'company'),
('Gemdale', 'China', 'company'),
('Helvetia Holding', 'Switzerland', 'company'),
('Lam Research', 'United States', 'company'),
('Bank of Yokohama', 'Japan', 'company'),
('Galp Energia', 'Portugal', 'company'),
('Intact Financial', 'Canada', 'company'),
('Amphenol', 'United States', 'company'),
('Raymond James Financial', 'United States', 'company'),
('Centene', 'United States', 'company'),
('Leucadia National', 'United States', 'company'),
('Dongbu Insurance', 'South Korea', 'company'),
('Neste Oil', 'Finland', 'company'),
('T Rowe Price', 'United States', 'company'),
('Kerry Group', 'Ireland', 'company'),
('Ventas', 'United States', 'company'),
('Qantas Airways', 'Australia', 'company'),
('Deutsche Wohnen', 'Germany', 'company'),
('Apache', 'United States', 'company'),
('Next', 'United Kingdom', 'company'),
('Alleghany', 'United States', 'company'),
('Comerica', 'United States', 'company'),
('Advanced Semiconductor', 'Taiwan', 'company'),
('Bank of India', 'India', 'company'),
('Salesforce.com', 'United States', 'company'),
('Novolipetsk Steel', 'Russia', 'company'),
('Industries Qatar', 'Qatar', 'company'),
('Gecina', 'France', 'company'),
('Japan Exchange Group', 'Japan', 'company'),
('China National Building', 'China', 'company'),
('Financiere de l"Odet', 'France', 'company'),
('Shanghai Pharmaceuticals', 'China', 'company'),
('SCANA', 'United States', 'company'),
('ALFA', 'Mexico', 'company'),
('Bidvest Group', 'South Africa', 'company'),
('Bank Negara Indonesia', 'Indonesia', 'company'),
('Symantec', 'United States', 'company'),
('Bank of Tianjin', 'China', 'company'),
('Advance Auto Parts', 'United States', 'company'),
('Clorox', 'United States', 'company'),
('China Steel', 'Taiwan', 'company'),
('CP All', 'Thailand', 'company'),
('Regeneron Pharmaceuticals', 'United States', 'company'),
('Adecco', 'Switzerland', 'company'),
('Kyushu Financial Group', 'Japan', 'company'),
('Seagate Technology', 'Ireland', 'company'),
('Wm Morrison Supermarkets', 'United Kingdom', 'company'),
('Mitsubishi UFJ Lease', 'Japan', 'company'),
('SGS', 'Switzerland', 'company'),
('Asustek Computer', 'Taiwan', 'company'),
('Nippon Yusen', 'Japan', 'company'),
('American Financial Group', 'United States', 'company'),
('Ctrip.com International', 'China', 'company'),
('Sinotex Investment & Development', 'China', 'company'),
('Meiji Holdings', 'Japan', 'company'),
('Mitsubishi Materials', 'Japan', 'company'),
('HD Supply Holdings', 'United States', 'company'),
('Interpublic Group', 'United States', 'company'),
('Saputo', 'Canada', 'company'),
('GAIL India', 'India', 'company'),
('Kajima', 'Japan', 'company'),
('Jeronimo Martins', 'Portugal', 'company'),
('Galaxy Entertainment', 'Hong Kong', 'company'),
('Cielo', 'Brazil', 'company'),
('Coca-Cola Enterprises', 'United States', 'company'),
('Netflix', 'United States', 'company'),
('China Gezhouba', 'China', 'company'),
('Asahi Glass', 'Japan', 'company'),
('Nitto Denko', 'Japan', 'company'),
('HollyFrontier', 'United States', 'company'),
('Hikvision', 'China', 'company'),
('Guangzhou Automobile Group', 'China', 'company'),
('Canadian Tire', 'Canada', 'company'),
('Marathon Oil', 'United States', 'company'),
('Terna', 'Italy', 'company'),
('El Puerto de Liverpool', 'Mexico', 'company'),
('Advanced Info Service', 'Thailand', 'company'),
('NVIDIA', 'United States', 'company'),
('Host Hotels & Resorts', 'United States', 'company'),
('EasyJet', 'United Kingdom', 'company'),
('Kyushu Electric Power', 'Japan', 'company'),
('Air France-KLM', 'France', 'company'),
('Amadeus IT Holdings', 'Spain', 'company'),
('Tokyo Electron', 'Japan', 'company'),
('Hankyu Hanshin Holdings', 'Japan', 'company'),
('Bashneft', 'Russia', 'company'),
('Arab National Bank', 'Saudi Arabia', 'company'),
('W&W-Wüstenrot', 'Germany', 'company'),
('Sandvik', 'Sweden', 'company'),
('Bank of Jinzhou', 'China', 'company'),
('VimpelCom', 'Netherlands', 'company'),
('Woodside Petroleum', 'Australia', 'company'),
('Power Finance', 'India', 'company'),
('Sun Pharma Industries', 'India', 'company'),
('Yamaha Motor', 'Japan', 'company'),
('Staples', 'United States', 'company'),
('Pentair', 'United Kingdom', 'company'),
('Netease', 'China', 'company'),
('Fluor', 'United States', 'company'),
('Harley-Davidson', 'United States', 'company'),
('Moody"s', 'United States', 'company'),
('JG Summit Holdings', 'Philippines', 'company'),
('Thai Beverage', 'Thailand', 'company'),
('Harbin Bank', 'China', 'company'),
('Shanghai Construction', 'China', 'company'),
('St. James"s Place', 'United Kingdom', 'company'),
('Delta Electronics', 'Taiwan', 'company'),
('Mondi', 'United Kingdom', 'company'),
('Royal Mail', 'United Kingdom', 'company'),
('SMC', 'Japan', 'company'),
('Rite Aid', 'United States', 'company'),
('PVH', 'United States', 'company'),
('Lend Lease Group', 'Australia', 'company'),
('RSA Insurance Group', 'United Kingdom', 'company'),
('Brambles', 'Australia', 'company'),
('Genworth Financial', 'United States', 'company'),
('Abertis', 'Spain', 'company'),
('Arch Capital Group', 'Bermuda', 'company'),
('Western Union', 'United States', 'company'),
('Legrand', 'France', 'company'),
('Attijariwafa Bank', 'Morocco', 'company'),
('Tenaris', 'Luxembourg', 'company'),
('Willis Towers Watson', 'United Kingdom', 'company'),
('AntarChile', 'Chile', 'company'),
('Motorola Solutions', 'United States', 'company'),
('Dover', 'United States', 'company'),
('Experian', 'Ireland', 'company'),
('Intuit', 'United States', 'company'),
('Bankinter', 'Spain', 'company'),
('Belgacom', 'Belgium', 'company'),
('Givaudan', 'Switzerland', 'company'),
('Kintetsu', 'Japan', 'company'),
('Idemitsu Kosan', 'Japan', 'company'),
('First Financial Holding', 'Taiwan', 'company'),
('Fortescue Metals Group', 'Australia', 'company'),
('Shin Kong Financial', 'Taiwan', 'company'),
('Shenzhen Overseas', 'China', 'company'),
('Lixil Group', 'Japan', 'company'),
('Community Health Systems', 'United States', 'company'),
('China Cosco Holdings', 'China', 'company'),
('NRG Energy', 'United States', 'company'),
('Autoliv', 'Sweden', 'company'),
('Electronic Arts', 'United States', 'company'),
('American Water Works', 'United States', 'company'),
('Perrigo', 'Ireland', 'company'),
('Roper Industries', 'United States', 'company'),
('Noble Group', 'Hong Kong', 'company'),
('BorgWarner', 'United States', 'company'),
('Zijin Mining Group', 'China', 'company'),
('Qatar Islamic Bank', 'Qatar', 'company'),
('Tata Steel', 'India', 'company'),
('Wuliangye Yibin', 'China', 'company'),
('Alaska Air Group', 'United States', 'company'),
('Uniqa', 'Austria', 'company'),
('Hoya', 'Japan', 'company'),
('Popular', 'United States', 'company'),
('Industrial Securities', 'China', 'company'),
('Oriental Land', 'Japan', 'company'),
('Doosan', 'South Korea', 'company'),
('Brenntag', 'Germany', 'company'),
('Vienna Insurance Group', 'Austria', 'company'),
('Banco Popolare', 'Italy', 'company'),
('CA', 'United States', 'company'),
('Renesas Electronics', 'Japan', 'company'),
('CenterPoint Energy', 'United States', 'company'),
('E-Trade Financial', 'United States', 'company'),
('Top Frontier Investment Holdings', 'Philippines', 'company'),
('Paychex', 'United States', 'company'),
('Vedanta Resources', 'United Kingdom', 'company'),
('Restaurant Brands International', 'Canada', 'company'),
('Caesars Entertainment', 'United States', 'company'),
('ITV', 'United Kingdom', 'company'),
('GS Holdings', 'South Korea', 'company'),
('Hyundai Engineering', 'South Korea', 'company'),
('Jiangxi Copper', 'China', 'company'),
('Shinsei Bank', 'Japan', 'company'),
('China Hongqiao Group', 'China', 'company'),
('Banca Mediolanum', 'Italy', 'company'),
('Banco Popular Espanol', 'Spain', 'company'),
('Grifols', 'Spain', 'company'),
('Rockwell Collins', 'United States', 'company'),
('Tenet Healthcare', 'United States', 'company'),
('Intuitive Surgical', 'United States', 'company'),
('Cerner', 'United States', 'company'),
('Masraf Al Rayan', 'Qatar', 'company'),
('SKF Group', 'Sweden', 'company'),
('Antero Resources', 'United States', 'company'),
('Starwood Hotels', 'United States', 'company'),
('KT&G', 'South Korea', 'company'),
('Brown-Forman', 'United States', 'company'),
('Shizuoka Bank', 'Japan', 'company'),
('Severstal', 'Russia', 'company'),
('Dangote Cement', 'Nigeria', 'company'),
('Jiangsu Yanghe Brewery', 'China', 'company'),
('Skyworks Solutions', 'United States', 'company'),
('Julius Baer Group', 'Switzerland', 'company'),
('Ayala Corporation', 'Philippines', 'company'),
('CJ Corp', 'South Korea', 'company'),
('Hebei Iron & Steel', 'China', 'company'),
('Chiba Bank', 'Japan', 'company'),
('Bombardier', 'Canada', 'company'),
('Hindalco Industries', 'India', 'company'),
('Monster Beverage', 'United States', 'company'),
('Global Logistic Properties', 'Singapore', 'company'),
('Rural Electrification', 'India', 'company'),
('Sun Art Retail Group', 'Hong Kong', 'company'),
('Analog Devices', 'United States', 'company'),
('Red Eléctrica', 'Spain', 'company'),
('Sojitz', 'Japan', 'company'),
('Signature Bank', 'United States', 'company'),
('Bunzl', 'United Kingdom', 'company'),
('Foot Locker', 'United States', 'company'),
('Manpower', 'United States', 'company'),
('Amorepacific', 'South Korea', 'company'),
('BPI', 'Philippines', 'company'),
('Norsk Hydro', 'Norway', 'company'),
('Barratt Developments', 'United Kingdom', 'company'),
('Tractor Supply', 'United States', 'company'),
('Genting', 'Malaysia', 'company'),
('Starwood Property Trust', 'United States', 'company'),
('Eletrobrás', 'Brazil', 'company'),
('CDW', 'United States', 'company'),
('Ezdan Holding Group', 'Qatar', 'company'),
('L-3 Communications', 'United States', 'company'),
('Wyndham Worldwide', 'United States', 'company'),
('Mead Johnson Nutrition', 'United States', 'company'),
('Colruyt', 'Belgium', 'company'),
('UC Rusal', 'Russia', 'company'),
('Century Tokyo Leasing', 'Japan', 'company'),
('Hainan Airlines', 'China', 'company'),
('LKQ', 'United States', 'company'),
('Chow Tai Fook Jewellery', 'Hong Kong', 'company'),
('Caltex Australia', 'Australia', 'company'),
('Crown Holdings', 'United States', 'company'),
('AutoNation', 'United States', 'company'),
('Kimco Realty', 'United States', 'company'),
('Origin Energy', 'Australia', 'company'),
('Delta Lloyd', 'Netherlands', 'company'),
('SanDisk', 'United States', 'company'),
('Bank of Chongqing', 'China', 'company'),
('Edwards Lifesciences', 'United States', 'company'),
('Pearson', 'United Kingdom', 'company'),
('Taiwan Cooperative Financial', 'Taiwan', 'company'),
('Seiko Epson', 'Japan', 'company'),
('Actelion', 'Switzerland', 'company'),
('Hua Nan Financial', 'Taiwan', 'company'),
('CF Industries Holdings', 'United States', 'company'),
('Check Point Software', 'Israel', 'company'),
('National Bank of Greece', 'Greece', 'company'),
('Union Bank of India', 'India', 'company'),
('Metro', 'Canada', 'company'),
('BS Financial Group', 'South Korea', 'company'),
('Molson Coors Brewing', 'United States', 'company'),
('Alstom', 'France', 'company'),
('Yanzhou Coal Mining', 'China', 'company'),
('Michael Kors Holdings', 'Hong Kong', 'company'),
('ICA Gruppen', 'Sweden', 'company'),
('Mitsui OSK Lines', 'Japan', 'company'),
('Technip', 'France', 'company'),
('DSM', 'Netherlands', 'company'),
('InterContinental Hotels', 'United Kingdom', 'company'),
('Noble Energy', 'United States', 'company'),
('Goldcorp', 'Canada', 'company'),
('Samsung SDS', 'South Korea', 'company'),
('Turkcell', 'Turkey', 'company'),
('Assurant', 'United States', 'company'),
('Petronas Chemicals', 'Malaysia', 'company'),
('Charoen Pokphand Foods', 'Thailand', 'company'),
('Direct Line Insurance', 'United Kingdom', 'company'),
('Arab Bank', 'Jordan', 'company'),
('Goodman Group', 'Australia', 'company'),
('Bank of Zhengzhou', 'China', 'company'),
('ARM Holdings', 'United Kingdom', 'company'),
('Li & Fung', 'Hong Kong', 'company'),
('Hindustan Petroleum', 'India', 'company'),
('Mashreq Bank', 'United Arab Emirates', 'company'),
('Hyundai Marine & Fire', 'South Korea', 'company'),
('Vicinity Centres', 'Australia', 'company'),
('BCI-Banco Credito', 'Chile', 'company'),
('Yamato Holdings', 'Japan', 'company'),
('Stockland Australia', 'Australia', 'company'),
('Electric Power Development', 'Japan', 'company'),
('Ralph Lauren', 'United States', 'company'),
('Masco', 'United States', 'company'),
('Airports of Thailand', 'Thailand', 'company'),
('Hertz Global Holdings', 'United States', 'company'),
('Dai Nippon Printing', 'Japan', 'company'),
('Hammerson', 'United Kingdom', 'company'),
('Industrial Alliance Insurance', 'Canada', 'company'),
('Sika', 'Switzerland', 'company'),
('United Utilities', 'United Kingdom', 'company'),
('Torchmark', 'United States', 'company'),
('E-mart', 'South Korea', 'company'),
('Inner Mongolia Baotou Steel', 'China', 'company'),
('Ingram Micro', 'United States', 'company'),
('Zoetis', 'United States', 'company'),
('Spirit AeroSystems', 'United States', 'company'),
('Expeditors International', 'United States', 'company'),
('Kobe Steel', 'Japan', 'company'),
('Banca MPS', 'Italy', 'company'),
('Fukuoka Financial Group', 'Japan', 'company'),
('Norwegian Cruise Line Holdings', 'United States', 'company'),
('Illumina', 'United States', 'company'),
('Shimano', 'Japan', 'company'),
('Signet Jewelers', 'Bermuda', 'company'),
('Hanesbrands', 'United States', 'company'),
('Pioneer Natural Resources', 'United States', 'company'),
('Hyosung', 'South Korea', 'company'),
('Toppan Printing', 'Japan', 'company'),
('Dassault Systemes', 'France', 'company'),
('Shionogi', 'Japan', 'company'),
('GKN', 'United Kingdom', 'company'),
('HCP', 'United States', 'company'),
('Aramark', 'United States', 'company'),
('MOL Hungarian Oil', 'Hungary', 'company'),
('JB Hunt Transport', 'United States', 'company'),
('MISC', 'Malaysia', 'company'),
('Eisai', 'Japan', 'company'),
('Electrolux Group', 'Sweden', 'company'),
('AVIC Capita', 'China', 'company'),
('Chugoku Electric Power', 'Japan', 'company'),
('BBMG', 'China', 'company'),
('China International Marine', 'China', 'company'),
('SES', 'Luxembourg', 'company'),
('Weatherford International', 'Switzerland', 'company'),
('Fortum', 'Finland', 'company'),
('Juniper Networks', 'United States', 'company'),
('Taylor Wimpey', 'United Kingdom', 'company'),
('Alexion Pharmaceuticals', 'United States', 'company'),
('Shaw Communications', 'Canada', 'company'),
('Jyske Bank', 'Denmark', 'company'),
('Jabil Circuit', 'United States', 'company'),
('Aeroports de Paris', 'France', 'company'),
('Ahli United Bank', 'Bahrain', 'company'),
('Sharp', 'Japan', 'company'),
('Naver', 'South Korea', 'company'),
('Hexagon', 'Sweden', 'company'),
('Kawasaki Heavy Industries', 'Japan', 'company'),
('Unicharm', 'Japan', 'company'),
('Commercial International Bank', 'Egypt', 'company'),
('Persimmon', 'United Kingdom', 'company'),
('UCB', 'Belgium', 'company'),
('Chipotle Mexican Grill', 'United States', 'company'),
('Ball', 'United States', 'company'),
('JetBlue Airways', 'United States', 'company'),
('Pandora', 'Denmark', 'company'),
('E.Sun Financial', 'Taiwan', 'company'),
('IndusInd Bank', 'India', 'company'),
('United Rentals', 'United States', 'company'),
('BCV Group', 'Switzerland', 'company'),
('China Merchants Holdings', 'Hong Kong', 'company'),
('Metropolitan Bank & Trust', 'Philippines', 'company'),
('News Corp', 'United States', 'company'),
('Aareal Bank', 'Germany', 'company'),
('China National Chemical', 'China', 'company'),
('ISS', 'Denmark', 'company'),
('Wuhan Iron & Steel', 'China', 'company'),
('Oneok', 'United States', 'company'),
('Idea Cellular', 'India', 'company'),
('Gudang Garam', 'Indonesia', 'company'),
('Smurfit Kappa Group', 'Ireland', 'company'),
('Medipal Holdings', 'Japan', 'company'),
('Taishin Financial Holdings', 'Taiwan', 'company'),
('Ametek', 'United States', 'company'),
('Changjiang Securities', 'China', 'company'),
('Smith & Nephew', 'United Kingdom', 'company'),
('Foncière des Régions', 'France', 'company'),
('Wolters Kluwer', 'Netherlands', 'company'),
('Newell Rubbermaid', 'United States', 'company'),
('China Life Insurance (Taiwan)', 'Taiwan', 'company'),
('RHB Capital', 'Malaysia', 'company'),
('Sealed Air', 'United States', 'company'),
('Arca Continental', 'Mexico', 'company'),
('Metalurgica Gerdau', 'Brazil', 'company'),
('Gjensidige Forsikring', 'Norway', 'company'),
('Saudi Hollandi Bank', 'Saudi Arabia', 'company'),
('LG Household & Health Care', 'South Korea', 'company'),
('Sekisui Chemical', 'Japan', 'company'),
('Chang Hwa Bank', 'Taiwan', 'company'),
('Klepierre', 'France', 'company'),
('New York Community', 'United States', 'company'),
('DCC', 'Ireland', 'company'),
('Weichai Power', 'China', 'company'),
('Phoenix Group Holdings', 'United Kingdom', 'company'),
('Transurban Group', 'Australia', 'company'),
('Whitbread', 'United Kingdom', 'company'),
('UBI Banca', 'Italy', 'company'),
('Shanghai Commercial & Savings Bank', 'Taiwan', 'company'),
('Brait', 'Malta', 'company'),
('Frontier Communications', 'United States', 'company'),
('Fastenal', 'United States', 'company'),
('Intu Properties', 'United Kingdom', 'company'),
('Sociedades Bolivar', 'Colombia', 'company'),
('Avis Budget Group', 'United States', 'company'),
('OTP Bank', 'Hungary', 'company'),
('LARGAN Precision', 'Taiwan', 'company'),
('Saudi Arabian Mining', 'Saudi Arabia', 'company'),
('Bank Muscat', 'Oman', 'company'),
('AECOM Technology', 'United States', 'company'),
('DSME', 'South Korea', 'company'),
('Verisk Analytics', 'United States', 'company'),
('Hasbro', 'United States', 'company'),
('Grupo Carso', 'Mexico', 'company'),
('Hong Leong Financial', 'Malaysia', 'company'),
('Zions Bancorp', 'United States', 'company'),
('Korean Air', 'South Korea', 'company'),
('Cemig', 'Brazil', 'company'),
('Wärtsilä', 'Finland', 'company'),
('Nintendo', 'Japan', 'company'),
('Hyundai Glovis', 'South Korea', 'company'),
('Kerry Properties', 'Hong Kong', 'company'),
('Teck Resources', 'Canada', 'company'),
('Sistema', 'Russia', 'company'),
('Terumo', 'Japan', 'company'),
('AGL Energy', 'Australia', 'company'),
('Oji Holdings', 'Japan', 'company'),
('Steel Authority of India', 'India', 'company'),
('Belle International Holdings', 'Hong Kong', 'company'),
('IDBI Bank', 'India', 'company'),
('Xilinx', 'United States', 'company'),
('Assured Guaranty', 'Bermuda', 'company'),
('NASDAQ OMX Group', 'United States', 'company'),
('Axis Capital Holdings', 'Bermuda', 'company'),
('East West Bancorp', 'United States', 'company'),
('Old Republic International', 'United States', 'company'),
('Bank Audi', 'Lebanon', 'company'),
('Sears Holdings', 'United States', 'company'),
('Turk Telekom', 'Turkey', 'company'),
('Iliad', 'France', 'company'),
('Pinnacle West', 'United States', 'company'),
('Union National Bank', 'United Arab Emirates', 'company'),
('Innolux', 'Taiwan', 'company'),
('Storebrand', 'Norway', 'company'),
('NSK', 'Japan', 'company'),
('SVB Financial Group', 'United States', 'company'),
('Mattel', 'United States', 'company'),
('Agilent Technologies', 'United States', 'company'),
('Oi', 'Brazil', 'company'),
('Dixons Carphone', 'United Kingdom', 'company'),
('Compal Electronics', 'Taiwan', 'company'),
('Olam International', 'Singapore', 'company'),
('Companhia Brasileira de Distribuicao', 'Brazil', 'company'),
('SL Green Realty', 'United States', 'company'),
('Wendel', 'France', 'company'),
('Almarai', 'Saudi Arabia', 'company'),
('Olympus', 'Japan', 'company'),
('Hengan International Group', 'China', 'company'),
('Visteon', 'United States', 'company'),
('China Grand Automotive Services', 'China', 'company'),
('KLA-Tencor', 'United States', 'company'),
('Harris', 'United States', 'company'),
('Meritz Financial Group', 'South Korea', 'company'),
('China Longyuan Power', 'China', 'company'),
('SinoPac Financial', 'Taiwan', 'company'),
('NiSource', 'United States', 'company'),
('Penske Automotive', 'United States', 'company'),
('Chesapeake Energy', 'United States', 'company'),
('IHI', 'Japan', 'company'),
('Lindt & Sprungli', 'Switzerland', 'company'),
('Petronas Gas', 'Malaysia', 'company'),
('Want Want China', 'China', 'company'),
('Aozora Bank', 'Japan', 'company'),
('Yuanta Financial Holding', 'Taiwan', 'company'),
('China Mengniu Dairy', 'China', 'company'),
('Ambac Financial Group', 'United States', 'company'),
('Novozymes', 'Denmark', 'company'),
('Dexia', 'Belgium', 'company'),
('AmTrust Financial Services', 'United States', 'company'),
('Nippon Express', 'Japan', 'company'),
('Geberit', 'Switzerland', 'company'),
('Shoprite Holdings', 'South Africa', 'company'),
('Entermate', 'South Korea', 'company'),
('McCormick', 'United States', 'company'),
('Equifax', 'United States', 'company'),
('Banca Popolare di Milano', 'Italy', 'company'),
('Trinity Industries', 'United States', 'company'),
('RusHydro', 'Russia', 'company'),
('TransDigm Group', 'United States', 'company'),
('JTEKT', 'Japan', 'company'),
('Latam Airlines', 'Chile', 'company'),
('PGE', 'Poland', 'company'),
('Darden Restaurants', 'United States', 'company'),
('Cosmo Energy Holdings', 'Japan', 'company'),
('Sino Land', 'Hong Kong', 'company'),
('Taiwan Mobile', 'Taiwan', 'company'),
('MegaFon', 'Russia', 'company'),
('Banco Davivienda', 'Colombia', 'company'),
('Continental Resources', 'United States', 'company'),
('Manila Electric', 'Philippines', 'company'),
('Linear Technology', 'United States', 'company'),
('Cintas', 'United States', 'company'),
('LIG Insurance', 'South Korea', 'company'),
('Sembcorp Industries', 'Singapore', 'company'),
('Alfresa Holdings', 'Japan', 'company'),
('HRG Group', 'United States', 'company'),
('American Capital Agency', 'United States', 'company'),
('Banco Comercial Portugues', 'Portugal', 'company'),
('Huntington Ingalls Industries', 'United States', 'company'),
('Inter Rao', 'Russia', 'company'),
('Bajaj Auto', 'India', 'company'),
('UGI', 'United States', 'company'),
('Remgro', 'South Africa', 'company'),
('China Communications Services', 'China', 'company'),
('Arthur J. Gallagher', 'United States', 'company'),
('PulteGroup', 'United States', 'company'),
('Quintiles Transnational', 'United States', 'company'),
('Celanese', 'United States', 'company'),
('AmBank Group', 'Malaysia', 'company'),
('Airgas', 'United States', 'company'),
('Waters', 'United States', 'company'),
('Ramsay Health Care', 'Australia', 'company'),
('BM&F Bovespa', 'Brazil', 'company'),
('GEA Group', 'Germany', 'company'),
('Banco Occidental', 'Venezuela', 'company'),
('Oceanwide Holdings', 'China', 'company'),
('Babcock International Group', 'United Kingdom', 'company'),
('OMRON', 'Japan', 'company'),
('Sino-Ocean Land Holdings', 'China', 'company'),
('Maxis', 'Malaysia', 'company'),
('City Developments', 'Singapore', 'company'),
('Kansas City Southern', 'United States', 'company'),
('Moscow Exchange', 'Russia', 'company'),
('Savola Group', 'Saudi Arabia', 'company'),
('Zenith Bank', 'Nigeria', 'company'),
('Nomos Bank', 'Russia', 'company'),
('Realty Income', 'United States', 'company'),
('Rexel', 'France', 'company'),
('Tech Data', 'United States', 'company'),
('STRABAG', 'Austria', 'company'),
('Alinma Bank', 'Saudi Arabia', 'company'),
('Zhengzhou Yutong Bus', 'China', 'company'),
('Central Bank of India', 'India', 'company'),
('Lundbergs', 'Sweden', 'company'),
('TonenGeneral Sekiyu', 'Japan', 'company'),
('3i Group', 'United Kingdom', 'company'),
('Suzuken', 'Japan', 'company'),
('Blom Bank', 'Lebanon', 'company'),
('Mizrahi Tefahot Bank', 'Israel', 'company'),
('Affiliated Managers Group', 'United States', 'company'),
('Abu Dhabi Islamic Bank', 'United Arab Emirates', 'company'),
('Bendigo & Adelaide Bank', 'Australia', 'company'),
('Tesla Motors', 'United States', 'company'),
('Shiseido', 'Japan', 'company'),
('OSRAM Licht', 'Germany', 'company'),
('Hankook Tire', 'South Korea', 'company'),
('SINOPEC Engineering (Group)', 'China', 'company'),
('Southwest Securities', 'China', 'company'),
('AGL Resources', 'United States', 'company'),
('Scripps Networks Interactive', 'United States', 'company'),
('Franshion Properties (China)', 'Hong Kong', 'company'),
('Sumitomo Metal Mining', 'Japan', 'company'),
('Hokuhoku Financial Group', 'Japan', 'company'),
('Hang Lung Group', 'Hong Kong', 'company'),
('Piraeus Bank', 'Greece', 'company'),
('Taiwan High Speed Rail', 'Taiwan', 'company'),
('Ingredion', 'United States', 'company'),
('Iida Group Holdings', 'Japan', 'company'),
('Banco Continental', 'Peru', 'company'),
('World Fuel Services', 'United States', 'company'),
('FleetCor Technologies', 'United States', 'company'),
('Accor', 'France', 'company'),
('Samsung SDI', 'South Korea', 'company'),
('Aspen Pharmacare Holdings', 'South Africa', 'company'),
('Cattolica Assicurazioni', 'Italy', 'company'),
('Commercial Bank of Qatar', 'Qatar', 'company'),
('Nürnberger', 'Germany', 'company'),
('Church & Dwight', 'United States', 'company'),
('DSV', 'Denmark', 'company'),
('Genting Hong Kong', 'Hong Kong', 'company'),
('ProSiebenSat1 Media', 'Germany', 'company'),
('BesTV New Media', 'China', 'company'),
('Mallinckrodt', 'Ireland', 'company'),
('Western Refining', 'United States', 'company'),
('Yamaguchi Financial', 'Japan', 'company'),
('Equinix', 'United States', 'company'),
('Westlake Chemical', 'United States', 'company'),
('Ningbo Port', 'China', 'company'),
('Foshan Haitian Flavouring and Food Company', 'China', 'company'),
('FMC Technologies', 'United States', 'company'),
('Newcrest Mining', 'Australia', 'company'),
('Kangmei Pharmaceutical', 'China', 'company'),
('Sunac China Holdings', 'China', 'company'),
('Shaanxi Coal Industry', 'China', 'company'),
('Tiffany & Co.', 'United States', 'company'),
('Concho Resources', 'United States', 'company'),
('Eurazeo', 'France', 'company'),
('Deutsche Pfandbriefbank', 'Germany', 'company'),
('Tokyu Fudosan', 'Japan', 'company'),
('Capita', 'United Kingdom', 'company'),
('Citrix Systems', 'United States', 'company'),
('Eurobank Ergasias', 'Greece', 'company'),
('Digital Realty Trust', 'United States', 'company'),
('MAp', 'Australia', 'company'),
('PLDT', 'Philippines', 'company'),
('Coach', 'United States', 'company'),
('Computer Sciences', 'United States', 'company'),
('Joyo Bank', 'Japan', 'company'),
('AU Optronics', 'Taiwan', 'company'),
('Alpha Bank', 'Greece', 'company'),
('Snap-on', 'United States', 'company'),
('China Resources Enterprise', 'Hong Kong', 'company'),
('Financial Street Holdings', 'China', 'company'),
('Enka', 'Turkey', 'company'),
('GameStop', 'United States', 'company'),
('Hiroshima Bank', 'Japan', 'company'),
('INTL FCStone', 'United States', 'company'),
('Nishi-Nippon City Bank', 'Japan', 'company'),
('Dassault Aviation', 'France', 'company'),
('Jiangsu Hengrui Medicine', 'China', 'company'),
('NMDC', 'India', 'company'),
('Kaisa Group Holdings', 'China', 'company'),
('Coca-Cola HBC', 'Switzerland', 'company'),
('Isetan Mitsukoshi Holdings', 'Japan', 'company'),
('New Hope Liuhe', 'China', 'company'),
('North Pacific Bank', 'Japan', 'company'),
('Hachijuni Bank', 'Japan', 'company'),
('77 Bank', 'Japan', 'company'),
('Alliant Energy', 'United States', 'company'),
('AAC Technologies Holdings', 'China', 'company'),
('China National Materials', 'China', 'company'),
('EMS-Chemie Holding', 'Switzerland', 'company'),
('TAQA', 'United Arab Emirates', 'company'),
('Arkema', 'France', 'company'),
('ONO Pharmaceutical', 'Japan', 'company'),
('Cheniere Energy', 'United States', 'company'),
('MMI Holdings', 'South Africa', 'company'),
('Syndicate Bank', 'India', 'company'),
('Guangdong Investment', 'Hong Kong', 'company'),
('Bank of Kyoto', 'Japan', 'company'),
('Partners Group Holding', 'Switzerland', 'company'),
('Banca Popolare dell"Emilia', 'Italy', 'company'),
('United Internet', 'Germany', 'company'),
('Suruga Bank', 'Japan', 'company'),
('EQT', 'United States', 'company'),
('Essex Property Trust', 'United States', 'company'),
('Chugoku Bank', 'Japan', 'company'),
('Zhejiang Material Industrial Zhongda Yuantong Group', 'China', 'company'),
('Burberry Group', 'United Kingdom', 'company'),
('Emirates Integrated Telecom', 'United Arab Emirates', 'company'),
('Gunma Bank', 'Japan', 'company'),
('Mitsui Chemicals', 'Japan', 'company'),
('Calpine', 'United States', 'company'),
('China Power International Development', 'China', 'company'),
('Hero Motocorp', 'India', 'company'),
('NetApp', 'United States', 'company'),
('Alrosa', 'Russia', 'company'),
('Yunnan Baiyao Group', 'China', 'company'),
('Frasers Centrepoint', 'Singapore', 'company'),
('Mercuries & Associates', 'Taiwan', 'company'),
('Dali Foods Group', 'China', 'company'),
('Koito Manufacturing', 'Japan', 'company'),
('Neptune Orient Lines', 'Singapore', 'company'),
('Packaging Corp of America', 'United States', 'company'),
('Shanxi Taigang Stainless', 'China', 'company'),
('Acciona', 'Spain', 'company'),
('FBN Holdings', 'Nigeria', 'company'),
('Nitori Holdings', 'Japan', 'company'),
('Sabre', 'United States', 'company'),
('Korea Zinc', 'South Korea', 'company'),
('Samsung Heavy Industries', 'South Korea', 'company'),
('Wistron', 'Taiwan', 'company'),
('Sumitomo Rubber', 'Japan', 'company'),
('Agile Property Holdings', 'Hong Kong', 'company'),
('Commercial Bank For Investment & Development Of Vietnam', 'Vietnam', 'company'),
('Iyo Bank', 'Japan', 'company'),
('Lupin', 'India', 'company'),
('Targa Resources Corp.', 'United States', 'company'),
('Ashland', 'United States', 'company'),
('CJ Cheiljedang', 'South Korea', 'company'),
('Alfa Laval', 'Sweden', 'company'),
('Israel Discount Bank', 'Israel', 'company'),
('Yamada Denki', 'Japan', 'company'),
('GCL System Integration Technology', 'China', 'company'),
('Public Power', 'Greece', 'company'),
('Empire', 'Canada', 'company'),
('Juroku Bank', 'Japan', 'company'),
('Indian Overseas Bank', 'India', 'company'),
('Ashikaga Holdings', 'Japan', 'company'),
('American Equity Investment', 'United States', 'company'),
('Quinenco', 'Chile', 'company'),
('Aldar Properties', 'United Arab Emirates', 'company'),
('Securitas', 'Sweden', 'company'),
('Cablevision Systems', 'United States', 'company'),
('Red Star Macalline Group', 'China', 'company'),
('Banco BPI', 'Portugal', 'company'),
('LG Uplus', 'South Korea', 'company'),
('Interactive Brokers Group', 'United States', 'company'),
('International Flavors & Fragrances', 'United States', 'company'),
('Showa Shell Sekiyu', 'Japan', 'company'),
('SK Networks', 'South Korea', 'company'),
('Supervalu', 'United States', 'company'),
('Corporacion Geo', 'Mexico', 'company'),
('Doha Bank', 'Qatar', 'company'),
('Dongxing Securities', 'China', 'company'),
('DGB Financial Group', 'South Korea', 'company'),
('GPT Group', 'Australia', 'company'),
('Areva', 'France', 'company'),
('Vertex Pharmaceuticals', 'United States', 'company'),
('DIA', 'Spain', 'company'),
('Toho Bank', 'Japan', 'company'),
('Ulta Salon Cosmetcs & Fragrance', 'United States', 'company'),
('Nippon Steel Trading', 'Japan', 'company'),
('BayWa', 'Germany', 'company'),
('Derwent London', 'United Kingdom', 'company'),
('Hanergy Thin Film Power Group', 'Hong Kong', 'company'),
('Yes Bank', 'India', 'company'),
('Nanto Bank', 'Japan', 'company'),
('Banco del Caribe, C.A. Banco Universal', 'Venezuela', 'company'),
('WPG Holdings', 'Taiwan', 'company'),
('X5 Retail Group', 'Russia', 'company'),
('Focus Media Information Technology', 'China', 'company'),
('Orkla', 'Norway', 'company'),
('Angang Steel', 'China', 'company'),
('Desarrolladora Homex', 'Mexico', 'company'),
('Endo', 'Ireland', 'company'),
('Hyakugo Bank', 'Japan', 'company'),
('People"s United Financial', 'United States', 'company'),
('Far Eastern New Century', 'Taiwan', 'company'),
('Liberbank', 'Spain', 'company'),
('Harman International', 'United States', 'company'),
('Pacific Corp', 'South Korea', 'company'),
('Microchip Technology', 'United States', 'company'),
('First Pacific', 'Hong Kong', 'company'),
('Ogaki Kyoritsu Bank', 'Japan', 'company'),
('Taiwan Business Bank', 'Taiwan', 'company'),
('Youngor Group', 'China', 'company'),
('Travis Perkins', 'United Kingdom', 'company'),
('Senshu Ikeda Holdings', 'Japan', 'company'),
('Virgin Money Holdings', 'United Kingdom', 'company'),
('Banco de Chile', 'Chile', 'company'),
('Damac Properties', 'United Arab Emirates', 'company'),
('Garmin', 'United States', 'company'),
('IMS Health Holdings', 'United States', 'company'),
('Heilan Home', 'China', 'company'),
('MGIC Investment', 'United States', 'company'),
('Shanghai Chengtou Holding', 'China', 'company'),
('Two Harbors Investment', 'United States', 'company'),
('NII Holdings', 'United States', 'company'),
('Thai Oil', 'Thailand', 'company'),
('Israel Corp', 'Israel', 'company'),
('ST Engineering', 'Singapore', 'company'),
('Tingyi Holding', 'China', 'company'),
('Fortune Brands Home & Security', 'United States', 'company'),
('Performance Food Group', 'United States', 'company'),
('Vereit', 'United States', 'company'),
('BOK Financial', 'United States', 'company'),
('JSW Steel', 'India', 'company'),
('Daishi Bank', 'Japan', 'company'),
('Tokyo TY Financial Group', 'Japan', 'company'),
('Pembina Pipeline', 'Canada', 'company'),
('VeriSign', 'United States', 'company'),
('Kingdom Holding', 'Saudi Arabia', 'company'),
('Jones Lang LaSalle', 'United States', 'company'),
('Shiga Bank', 'Japan', 'company'),
('Orient', 'Japan', 'company'),
('Catcher Technology', 'Taiwan', 'company'),
('Amdocs', 'United States', 'company'),
('Saudi Investment Bank', 'Saudi Arabia', 'company'),
('Segro', 'United Kingdom', 'company'),
('Halyk Bank', 'Kazakhstan', 'company'),
('Credito Emiliano', 'Italy', 'company'),
('Tongling Nonferrous Metals', 'China', 'company'),
('San-In Godo Bank', 'Japan', 'company'),
('Bank of Qingdao', 'China', 'company'),
('First Niagara Financial', 'United States', 'company'),
('Office Depot', 'United States', 'company'),
('Hyakujushi Bank', 'Japan', 'company'),
('Chinese Estates', 'Hong Kong', 'company'),
('Admiral Group plc', 'United Kingdom', 'company'),
('Umicore', 'Belgium', 'company'),
('USG', 'United States', 'company'),
('Banca Popolare di Sondrio', 'Italy', 'company'),
('Habib Bank', 'Pakistan', 'company'),
('Lazard', 'Bermuda', 'company'),
('Molina Healthcare', 'United States', 'company'),
('Basler Kantonalbank', 'Switzerland', 'company'),
('Dufry AG', 'Switzerland', 'company'),
('JC Penney', 'United States', 'company'),
('Saudi Arabian Fertilizers', 'Saudi Arabia', 'company'),
('WellCare Health Plans', 'United States', 'company'),
('Great Portland Estates', 'United Kingdom', 'company'),
('Vietin Bank', 'Vietnam', 'company'),
('Chicago Bridge & Iron', 'Netherlands', 'company'),
('NVR,', 'United States', 'company'),
('FCC', 'Spain', 'company'),
('Keiyo Bank', 'Japan', 'company'),
('Mettler-Toledo International', 'United States', 'company'),
('CNO Financial Group', 'United States', 'company'),
('UCO Bank', 'India', 'company'),
('Guaranty Trust Bank', 'Nigeria', 'company'),
('Total System Services', 'United States', 'company'),
('Nippon Paper Industries', 'Japan', 'company'),
('Cullen/Frost Bankers', 'United States', 'company'),
('Shanghai International Airport', 'China', 'company'),
('Bank Aljazira', 'Saudi Arabia', 'company'),
('Kiyo Bank', 'Japan', 'company'),
('Ashtead Group', 'United Kingdom', 'company'),
('Coty', 'United States', 'company'),
('KWG Property Holding', 'Hong Kong', 'company'),
('RiseSun Real Estate Development', 'China', 'company'),
('Macerich', 'United States', 'company'),
('Techtronic Industries', 'Hong Kong', 'company'),
('Banca Transilvania', 'Romania', 'company'),
('Hokkoku Bank', 'Japan', 'company'),
('President Chain Store', 'Taiwan', 'company'),
('Xinjiang Goldwind Science & Technology', 'China', 'company'),
('Allahabad Bank', 'India', 'company'),
('Korea Investment Holdings', 'South Korea', 'company'),
('Leshi Internet Information & Technology Corp. Beijing', 'China', 'company'),
('Jacobs Engineering', 'United States', 'company'),
('SYNNEX', 'United States', 'company'),
('Hanwa', 'Japan', 'company'),
('Banque nationale de Belgique', 'Belgium', 'company'),
('Grupo Galicia', 'Argentina', 'company'),
('Valspar', 'United States', 'company'),
('Joint Stock Commercial Bank for Foreign Trade of Vietnam', 'Vietnam', 'company'),
('Banque Centrale Populaire', 'Morocco', 'company'),
('Musashino Bank', 'Japan', 'company'),
('Corporation Bank', 'India', 'company'),
('PBF Energy', 'United States', 'company'),
('Sysmex', 'Japan', 'company'),
('Shanghai Industrial Holdings', 'China', 'company'),
('Noble', 'Switzerland', 'company'),
('Varian Medical Systems', 'United States', 'company'),
('Bank of Queensland', 'Australia', 'company'),
('NH Investment & Securities', 'South Korea', 'company'),
('SNC-Lavalin Group', 'Canada', 'company'),
('Polaris Industries', 'United States', 'company'),
('Hanover Insurance Group', 'United States', 'company'),
('Coloplast', 'Denmark', 'company'),
('Ryder System', 'United States', 'company'),
('GS Engineering', 'South Korea', 'company'),
('Murphy USA', 'United States', 'company'),
('XPO Logistics', 'United States', 'company'),
('Zhuzhou CSR Times Electric', 'China', 'company'),
('Oriental Bank of Commerce', 'India', 'company'),
('Nelnet', 'United States', 'company'),
('Shanghai RAAS Blood Products', 'China', 'company'),
('Reliance Steel', 'United States', 'company'),
('Haseko', 'Japan', 'company'),
('Kawasaki Kisen Kaisha', 'Japan', 'company'),
('LinkedIn', 'United States', 'company'),
('Enagas', 'Spain', 'company'),
('Bolsas & Mercados', 'Spain', 'company'),
('Daewoo Securities', 'South Korea', 'company'),
('JB Financial Group', 'South Korea', 'company'),
('Inventec', 'Taiwan', 'company'),
('Barwa Real Estate', 'Qatar', 'company'),
('Smiths Group', 'United Kingdom', 'company'),
('Western Securities', 'China', 'company'),
('Bohai Financial Investment Holding', 'China', 'company'),
('Golden Agri-Resources', 'Singapore', 'company'),
('Luzerner Kantonalbank', 'Switzerland', 'company'),
('Sonova Holding', 'Switzerland', 'company'),
('First Solar,', 'United States', 'company'),
('US Steel', 'United States', 'company'),
('Vipshop Holdings', 'China', 'company'),
('Thomas Cook Group', 'United Kingdom', 'company'),
('Banca CARIGE', 'Italy', 'company'),
('Dick"s Sporting Goods', 'United States', 'company'),
('Petro Rabigh', 'Saudi Arabia', 'company'),
('Prada', 'Italy', 'company'),
('Soochow Securities', 'China', 'company'),
('Jabal Omar Development', 'Saudi Arabia', 'company'),
('CR Bard', 'United States', 'company'),
('Delek Group', 'Israel', 'company'),
('Berkeley Group Holdings', 'United Kingdom', 'company'),
('BioMarin Pharmaceutical', 'United States', 'company'),
('Latour Investment', 'Sweden', 'company'),
('RMB Holdings', 'South Africa', 'company'),
('Migdal Insurance', 'Israel', 'company'),
('FIBI Holdings', 'Israel', 'company'),
('Aurubis', 'Germany', 'company'),
('East Money Information', 'China', 'company'),
('Huntsman', 'United States', 'company'),
('K+S', 'Germany', 'company'),
('Workday', 'United States', 'company'),
('Permanent TSB Group', 'Ireland', 'company'),
('Konica Minolta', 'Japan', 'company'),
('Inchcape', 'United Kingdom', 'company'),
('Amerco', 'United States', 'company'),
('Kuwait Projects', 'Kuwait', 'company'),
('Air Canada', 'Canada', 'company'),
('Jazz Pharmaceuticals', 'Ireland', 'company'),
('PacWest Bancorp', 'United States', 'company'),
('First Citizens BancShares', 'United States', 'company'),
('Vulcan Materials', 'United States', 'company'),
('LG International', 'South Korea', 'company'),
('Guangdong Electric Power', 'China', 'company'),
('St Galler Kantonalbank', 'Switzerland', 'company'),
('Wanda Cinema Line', 'China', 'company'),
('Inotera Memories', 'Taiwan', 'company'),
('Columbia Pipeline Group', 'United States', 'company'),
('Dr. Reddy"s Laboratories', 'India', 'company'),
('China Great Wall Computer', 'China', 'company'),
('Dentsply Sirona', 'United States', 'company'),
('Toyota Boshoku', 'Japan', 'company'),
('Andritz', 'Austria', 'company'),
('Japan Securities', 'Japan', 'company'),
('CSN', 'Brazil', 'company'),
('China Development Financial', 'Taiwan', 'company'),
('Hokkaido Electric Power', 'Japan', 'company'),
('Kangwon Land', 'South Korea', 'company'),
('Incyte', 'United States', 'company'),
('Indian Bank', 'India', 'company'),
('Fibra Uno', 'Mexico', 'company'),
('Hudson"s Bay', 'Canada', 'company'),
('iHeartMedia', 'United States', 'company'),
('Sichuan Chuantou Energy', 'China', 'company'),
('Great Eagle Holdings', 'Hong Kong', 'company'),
('IHH Healthcare', 'Malaysia', 'company'),
('Zain', 'Kuwait', 'company'),
('Aroundtown Property Holdings', 'Germany', 'company'),
('Bank of Nagoya', 'Japan', 'company'),
('Canadian Utilities', 'Canada', 'company'),
('Empresas CMPC', 'Chile', 'company'),
('SEIBU', 'Japan', 'company'),
('Galenica', 'Switzerland', 'company'),
('Tech Mahindra', 'India', 'company'),
('Andhra Bank', 'India', 'company'),
('Crescent Point Energy', 'Canada', 'company'),
('NEXON', 'Japan', 'company'),
('Phosagro', 'Russia', 'company'),
('Pou Chen', 'Taiwan', 'company'),
('ResMed', 'United States', 'company'),
('Makita', 'Japan', 'company'),
('TMB Bank', 'Thailand', 'company'),
('Aboitiz Equity Ventures', 'Philippines', 'company'),
('Eutelsat Communications', 'France', 'company'),
('RR Donnelley & Sons', 'United States', 'company'),
('Minato Bank', 'Japan', 'company'),
('ICAP', 'United Kingdom', 'company'),
('Credito Valtellinese', 'Italy', 'company'),
('Synovus Financial', 'United States', 'company'),
('Millicom International', 'Luxembourg', 'company'),
('E-L Financial', 'Canada', 'company'),
('Sanmina-SCI', 'United States', 'company'),
('Martin Marietta Materials', 'United States', 'company'),
('Red Hat', 'United States', 'company'),
('Seadrill', 'Bermuda', 'company'),
('DVB Bank', 'Germany', 'company'),
('United Therapeutics', 'United States', 'company'),
('Core-Mark Holding Company', 'United States', 'company'),
('Beijing Capital Development', 'China', 'company'),
('Laurentian Bank', 'Canada', 'company'),
('CST Brands', 'United States', 'company'),
('SBI Holdings', 'Japan', 'company'),
('Thanachart Capital', 'Thailand', 'company'),
('TPV Technology', 'Hong Kong', 'company'),
('Alps Electric Co', 'Japan', 'company'),
('Arab Banking', 'Bahrain', 'company'),
('Associated Banc-Corp', 'United States', 'company'),
('BMCE Bank', 'Morocco', 'company'),
('Autodesk', 'United States', 'company'),
('BEKB-BCBE', 'Switzerland', 'company'),
('Jaccs', 'Japan', 'company'),
('Quanta Services', 'United States', 'company'),
('Wintime Energy', 'China', 'company'),
('Dah Sing Financial Holdings', 'Hong Kong', 'company'),
('Prosperity Bancshares', 'United States', 'company'),
('Ivanhoe Mines', 'Canada', 'company'),
('Pang Da Automobile Trade', 'China', 'company'),
('Wynn Resorts', 'United States', 'company'),
('Rede Empresas', 'Brazil', 'company'),
('Shaftesbury', 'United Kingdom', 'company'),
('Adani Enterprises', 'India', 'company'),
('China Agri-Industries', 'China', 'company'),
('Group 1 Automotive', 'United States', 'company'),
('Palo Alto Networks,', 'United States', 'company'),
('Westinghouse Air Brake Technologies', 'United States', 'company'),
('Oil & Gas Development', 'Pakistan', 'company'),
('Akamai Technologies', 'United States', 'company'),
('Hanwha Chemical', 'South Korea', 'company'),
('SBA Communications', 'United States', 'company'),
